IF EXISTS (SELECT * FROM sysobjects 
           WHERE id = OBJECT_ID(N'[kelso].[vsp_brisnet_xrdInsert]') 
              AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE [kelso].[vsp_brisnet_xrdInsert]
GO

CREATE PROCEDURE [kelso].[vsp_brisnet_xrdInsert]
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @CountRecords INT = 0;

	SELECT @CountRecords = COUNT(1)
	FROM kelso.brisnet_xrd_staging S
	JOIN kelso.brisnet_xrd XRD ON XRD.RaceDt = S.RaceDt AND XRD.TrackCd = S.TrackCd AND XRD.HorseName = S.HorseName;

	IF @CountRecords = 0
	BEGIN
		INSERT INTO kelso.brisnet_xrd (
									RaceId,
									TrackCd,
									RaceDt,
									RaceNum,
									ReservedString1,
									Surface,
									ReservedString2,
									ReservedString3,
									ReservedString4,
									ReservedString5,
									ReservedString6,
									ReservedString7,
									ReservedString8,
									ReservedString9,
									ReservedString10,
									ReservedString11,
									FinalTime,
									TrackCondition,
									PostPosition,
									EntryFlag,
									HorseId,
									HorseName,
									ReservedString12,
									ReservedString13,
									ReservedString14,
									ReservedString15,
									ReservedString16,
									ReservedString17,
									ReservedString18,
									ReservedString19,
									ReservedString20,
									FinishPosition,
									ReservedString21,
									WagerType10,
									WagerType11,
									WagerType12,
									WagerType13,
									WagerType14,
									HorseOdd,
									ReservedString22,
									ReservedString23,
									ReservedString24,
									ReservedString25,
									ReservedString26,
									ReservedString27,
									ReservedString28,
									ReservedString29,
									ReservedString30,
									ReservedString31,
									starter_field_size,
									official_finish_position,
									official_program_num,
									ReservedString32,
									ReservedString33,
									ReservedString34,
									ReservedString35,
									WinningNums10,
									WinningNums11,
									WinningNums12,
									WinningNums13,
									WinningNums14,
									TwoDollarsPayoff10,
									TwoDollarsPayoff11,
									TwoDollarsPayoff12,
									TwoDollarsPayoff13,
									TwoDollarsPayoff14,
									Pool10,
									Pool11,
									Pool12,
									Pool13,
									Pool14,
									BetAmt10,
									BetAmt11,
									BetAmt12,
									BetAmt13,
									BetAmt14,
									TwoDollarsWinPayOff,
									TwoDollarsPlacePayOff,
									TwoDollarsShowPayOff,
									WagerType1,
									WagerType2,
									WagerType3,
									WagerType4,
									WagerType5,
									WagerType6,
									WagerType7,
									WagerType8,
									WagerType9,
									WinningNums1,
									WinningNums2,
									WinningNums3,
									WinningNums4,
									WinningNums5,
									WinningNums6,
									WinningNums7,
									WinningNums8,
									WinningNums9,
									TwoDollarsPayoff1,
									TwoDollarsPayoff2,
									TwoDollarsPayoff3,
									TwoDollarsPayoff4,
									TwoDollarsPayoff5,
									TwoDollarsPayoff6,
									TwoDollarsPayoff7,
									TwoDollarsPayoff8,
									TwoDollarsPayoff9,
									Pool1,
									Pool2,
									Pool3,
									Pool4,
									Pool5,
									Pool6,
									Pool7,
									Pool8,
									Pool9,
									BetAmt1,
									BetAmt2,
									BetAmt3,
									BetAmt4,
									BetAmt5,
									BetAmt6,
									BetAmt7,
									BetAmt8,
									BetAmt9,
									ReservedString36,
									ReservedString37,
									ReservedString38,
									ReservedString39,
									ReservedString40,
									ReservedString41,
									ReservedString42,
									ReservedString43,
									ReservedString44,
									ReservedString45,
									ReservedString46,
									ReservedString47,
									ReservedString48,
									ReservedString49,
									ReservedString50,
									ReservedString51,
									ReservedString52,
									ReservedString53,
									ReservedString54,
									ReservedString55,
									ReservedString56,
									ReservedString57,
									ReservedString58,
									ReservedString59,
									ReservedString60,
									ReservedString61,
									ReservedString62,
									ReservedString63,
									ReservedString64,
									ReservedString65,
									ReservedString66,
									ReservedString67,
									ReservedString68,
									ReservedString69,
									ReservedString70,
									ReservedString71,
									ReservedString72,
									ReservedString73,
									ReservedString74,
									ReservedString75,
									ReservedString76,
									ReservedString77,
									ReservedString78,
									ReservedString79,
									ReservedString80,
									ReservedString81,
									ReservedString82,
									ReservedString83,
									ReservedString84,
									ReservedString85,
									ReservedString86,
									ReservedString87,
									ReservedString88,
									ReservedString89,
									ReservedString90,
									ReservedString91,
									ReservedString92,
									ReservedString93,
									ReservedString94,
									ReservedString95,
									ReservedString96,
									ReservedString97,
									ReservedString98,
									ReservedString99,
									ReservedString100,
									ReservedString101,
									ReservedString102,
									ReservedString103,
									ReservedString104,
									ReservedString105,
									ReservedString106,
									ReservedString107,
									ReservedString108,
									ReservedString109,
									ReservedString110,
									ReservedString111,
									ReservedString112,
									ReservedString113,
									ReservedString114,
									ReservedString115,
									ReservedString116,
									ReservedString117,
									ReservedString118,
									ReservedString119,
									ReservedString120,
									ReservedString121,
									ReservedString122,
									ReservedString123,
									ReservedString124,
									ReservedString125,
									ReservedString126,
									ReservedString127,
									ReservedString128,
									ReservedString129,
									ReservedString130,
									ReservedString131,
									ReservedString132,
									ReservedString133,
									ReservedString134,
									ReservedString135,
									ReservedString136,
									ReservedString137,
									ReservedString138,
									ReservedString139,
									ReservedString140,
									ReservedString141,
									ReservedString142,
									ReservedString143,
									ReservedString144,
									ReservedString145,
									ReservedString146,
									ReservedString147,
									ReservedString148,
									ReservedString149,
									ReservedString150,
									ReservedString151,
									ReservedString152,
									ReservedString153,
									ReservedString154,
									ReservedString155,
									ReservedString156,
									ReservedString157,
									ReservedString158,
									ReservedString159,
									ReservedString160,
									ReservedString161,
									ReservedString162,
									ReservedString163,
									ReservedString164,
									ReservedString165,
									ReservedString166,
									ReservedString167
								  )
					SELECT RP.RaceId,
						   S.TrackCd,
						   S.RaceDt,
						   S.RaceNum,
						   S.ReservedString1,
						   S.Surface,
						   S.ReservedString2,
						   S.ReservedString3,
						   S.ReservedString4,
						   S.ReservedString5,
						   S.ReservedString6,
						   S.ReservedString7,
						   S.ReservedString8,
						   S.ReservedString9,
						   S.ReservedString10,
						   S.ReservedString11,
						   CASE WHEN (S.FinalTime IS NULL OR LEN(S.FinalTime) = 0) THEN 0 ELSE CAST(S.FinalTime AS DECIMAL(18,2)) END,
						   S.TrackCondition,
						   S.PostPosition,
						   S.EntryFlag,
						   RP.HorseId,
						   S.HorseName,
						   S.ReservedString12,
						   S.ReservedString13,
						   S.ReservedString14,
						   S.ReservedString15,
						   S.ReservedString16,
						   S.ReservedString17,
						   S.ReservedString18,
						   S.ReservedString19,
						   S.ReservedString20,
						   S.FinishPosition,
						   S.ReservedString21,
						   S.WagerType10,
						   S.WagerType11,
						   S.WagerType12,
						   S.WagerType13,
						   S.WagerType14,
						   CASE WHEN (S.HorseOdd IS NULL OR LEN(S.HorseOdd) = 0) THEN 0 ELSE CAST(S.HorseOdd AS DECIMAL(18,2)) END,
						   S.ReservedString22,
						   S.ReservedString23,
						   S.ReservedString24,
						   S.ReservedString25,
						   S.ReservedString26,
						   S.ReservedString27,
						   S.ReservedString28,
						   S.ReservedString29,
						   S.ReservedString30,
						   S.ReservedString31,
						   S.starter_field_size,
						   S.official_finish_position,
						   S.official_program_num,
						   S.ReservedString32,
						   S.ReservedString33,
						   S.ReservedString34,
						   S.ReservedString35,
						   S.WinningNums10,
						   S.WinningNums11,
						   S.WinningNums12,
						   S.WinningNums13,
						   S.WinningNums14,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff10, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff10 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff11, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff11 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff12, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff12 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff13, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff13 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff14, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff14 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool10, '') = '' THEN 0 ELSE CAST(S.Pool10 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool11, '') = '' THEN 0 ELSE CAST(S.Pool11 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool12, '') = '' THEN 0 ELSE CAST(S.Pool12 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool13, '') = '' THEN 0 ELSE CAST(S.Pool13 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool14, '') = '' THEN 0 ELSE CAST(S.Pool14 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt10, '') = '' THEN 0 ELSE CAST(S.BetAmt10 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt11, '') = '' THEN 0 ELSE CAST(S.BetAmt11 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt12, '') = '' THEN 0 ELSE CAST(S.BetAmt12 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt13, '') = '' THEN 0 ELSE CAST(S.BetAmt13 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt14, '') = '' THEN 0 ELSE CAST(S.BetAmt14 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsWinPayOff, '') = '' THEN 0 ELSE CAST(S.TwoDollarsWinPayOff AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPlacePayOff, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPlacePayOff AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsShowPayOff, '') = '' THEN 0 ELSE CAST(S.TwoDollarsShowPayOff AS DECIMAL(18,2)) END,
						   S.WagerType1,
						   S.WagerType2,
						   S.WagerType3,
						   S.WagerType4,
						   S.WagerType5,
						   S.WagerType6,
						   S.WagerType7,
						   S.WagerType8,
						   S.WagerType9,
						   S.WinningNums1,
						   S.WinningNums2,
						   S.WinningNums3,
						   S.WinningNums4,
						   S.WinningNums5,
						   S.WinningNums6,
						   S.WinningNums7,
						   S.WinningNums8,
						   S.WinningNums9,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff1, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff1 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff2, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff2 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff3, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff3 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff4, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff4 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff5, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff5 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff6, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff6 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff7, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff7 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff8, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff8 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.TwoDollarsPayoff9, '') = '' THEN 0 ELSE CAST(S.TwoDollarsPayoff9 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool1, '') = '' THEN 0 ELSE CAST(S.Pool1 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool2, '') = '' THEN 0 ELSE CAST(S.Pool2 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool3, '') = '' THEN 0 ELSE CAST(S.Pool3 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool4, '') = '' THEN 0 ELSE CAST(S.Pool4 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool5, '') = '' THEN 0 ELSE CAST(S.Pool5 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool6, '') = '' THEN 0 ELSE CAST(S.Pool6 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool7, '') = '' THEN 0 ELSE CAST(S.Pool7 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool8, '') = '' THEN 0 ELSE CAST(S.Pool8 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.Pool9, '') = '' THEN 0 ELSE CAST(S.Pool9 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt1, '') = '' THEN 0 ELSE CAST(S.BetAmt1 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt2, '') = '' THEN 0 ELSE CAST(S.BetAmt2 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt3, '') = '' THEN 0 ELSE CAST(S.BetAmt3 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt4, '') = '' THEN 0 ELSE CAST(S.BetAmt4 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt5, '') = '' THEN 0 ELSE CAST(S.BetAmt5 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt6, '') = '' THEN 0 ELSE CAST(S.BetAmt6 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt7, '') = '' THEN 0 ELSE CAST(S.BetAmt7 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt8, '') = '' THEN 0 ELSE CAST(S.BetAmt8 AS DECIMAL(18,2)) END,
						   CASE WHEN ISNULL(S.BetAmt9, '') = '' THEN 0 ELSE CAST(S.BetAmt9 AS DECIMAL(18,2)) END,
						   S.ReservedString36,
						   S.ReservedString37,
						   S.ReservedString38,
						   S.ReservedString39,
						   S.ReservedString40,
						   S.ReservedString41,
						   S.ReservedString42,
						   S.ReservedString43,
						   S.ReservedString44,
						   S.ReservedString45,
						   S.ReservedString46,
						   S.ReservedString47,
						   S.ReservedString48,
						   S.ReservedString49,
						   S.ReservedString50,
						   S.ReservedString51,
						   S.ReservedString52,
						   S.ReservedString53,
						   S.ReservedString54,
						   S.ReservedString55,
						   S.ReservedString56,
						   S.ReservedString57,
						   S.ReservedString58,
						   S.ReservedString59,
						   S.ReservedString60,
						   S.ReservedString61,
						   S.ReservedString62,
						   S.ReservedString63,
						   S.ReservedString64,
						   S.ReservedString65,
						   S.ReservedString66,
						   S.ReservedString67,
						   S.ReservedString68,
						   S.ReservedString69,
						   S.ReservedString70,
						   S.ReservedString71,
						   S.ReservedString72,
						   S.ReservedString73,
						   S.ReservedString74,
						   S.ReservedString75,
						   S.ReservedString76,
						   S.ReservedString77,
						   S.ReservedString78,
						   S.ReservedString79,
						   S.ReservedString80,
						   S.ReservedString81,
						   S.ReservedString82,
						   S.ReservedString83,
						   S.ReservedString84,
						   S.ReservedString85,
						   S.ReservedString86,
						   S.ReservedString87,
						   S.ReservedString88,
						   S.ReservedString89,
						   S.ReservedString90,
						   S.ReservedString91,
						   S.ReservedString92,
						   S.ReservedString93,
						   S.ReservedString94,
						   S.ReservedString95,
						   S.ReservedString96,
						   S.ReservedString97,
						   S.ReservedString98,
						   S.ReservedString99,
						   S.ReservedString100,
						   S.ReservedString101,
						   S.ReservedString102,
						   S.ReservedString103,
						   S.ReservedString104,
						   S.ReservedString105,
						   S.ReservedString106,
						   S.ReservedString107,
						   S.ReservedString108,
						   S.ReservedString109,
						   S.ReservedString110,
						   S.ReservedString111,
						   S.ReservedString112,
						   S.ReservedString113,
						   S.ReservedString114,
						   S.ReservedString115,
						   S.ReservedString116,
						   S.ReservedString117,
						   S.ReservedString118,
						   S.ReservedString119,
						   S.ReservedString120,
						   S.ReservedString121,
						   S.ReservedString122,
						   S.ReservedString123,
						   S.ReservedString124,
						   S.ReservedString125,
						   S.ReservedString126,
						   S.ReservedString127,
						   S.ReservedString128,
						   S.ReservedString129,
						   S.ReservedString130,
						   S.ReservedString131,
						   S.ReservedString132,
						   S.ReservedString133,
						   S.ReservedString134,
						   S.ReservedString135,
						   S.ReservedString136,
						   S.ReservedString137,
						   S.ReservedString138,
						   S.ReservedString139,
						   S.ReservedString140,
						   S.ReservedString141,
						   S.ReservedString142,
						   S.ReservedString143,
						   S.ReservedString144,
						   S.ReservedString145,
						   S.ReservedString146,
						   S.ReservedString147,
						   S.ReservedString148,
						   S.ReservedString149,
						   S.ReservedString150,
						   S.ReservedString151,
						   S.ReservedString152,
						   S.ReservedString153,
						   S.ReservedString154,
						   S.ReservedString155,
						   S.ReservedString156,
						   S.ReservedString157,
						   S.ReservedString158,
						   S.ReservedString159,
						   S.ReservedString160,
						   S.ReservedString161,
						   S.ReservedString162,
						   S.ReservedString163,
						   S.ReservedString164,
						   S.ReservedString165,
						   S.ReservedString166,
						   S.ReservedString167
					FROM kelso.brisnet_xrd_staging S
						LEFT JOIN kelso.brisnet_RaceParticipants rp ON rp.TrackCd = s.TrackCd AND rp.RaceDt = S.RaceDt AND rp.HorseName = S.HorseName 
					WHERE NOT EXISTS (
										SELECT *
										FROM kelso.brisnet_xrd
										WHERE RaceDt = S.RaceDt
											  AND TrackCd = S.TrackCd
											  AND RaceNum = S.RaceNum
									 );
	END;
END;

GO