IF EXISTS (SELECT * FROM sysobjects 
           WHERE id = OBJECT_ID(N'[kelso].[vsp_EntMerge]') 
              AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE [kelso].[vsp_EntMerge]
GO

CREATE PROCEDURE [kelso].[vsp_EntMerge]
AS
BEGIN
	SET NOCOUNT ON;

	MERGE INTO kelso.ent E
	USING (
			SELECT *
			FROM kelso.ent_staging 
		  ) S
	ON S.RaceDt = E.RaceDt
	   AND S.TrackCd = E.TrackCd
	   AND S.RaceNum = E.RaceNum
	   AND S.HorseName = E.HorseName
	WHEN MATCHED THEN
		UPDATE
			SET E.PolePosition = S.PolePosition,
				E.MorningLine = S.MorningLine, 
				E.PaceLines = S.PaceLines, 
				E.EntryChar = S.EntryChar, 
				E.ScratchFlagInd = S.ScratchFlagInd, 
				E.CurrentYr = S.CurrentYr, 
				E.StartsThisYr = S.StartsThisYr, 
				E.WinThisYr = S.WinThisYr, 
				E.PlacesThisYr = S.PlacesThisYr, 
				E.ShowsThisYr = S.ShowsThisYr, 
				E.EarningThisYr = S.EarningThisYr, 
				E.PrevYearForEarning = S.PrevYearForEarning, 
				E.StartsPrevYr = S.StartsPrevYr, 
				E.WinPrevYr = S.WinPrevYr, 
				E.PlacesPrevYr = S.PlacesPrevYr, 
				E.ShowsPrevYr = S.ShowsPrevYr, 
				E.EarningPrevYr = S.EarningPrevYr, 
				E.OwnerName = S.OwnerName, 
				E.Color = S.Color,
				E.YearBorn = S.YearBorn, 
				E.MonthBorn = S.MonthBorn, 
				E.StateBredInd = S.StateBredInd, 
				E.Age = S.Age, 
				E.Sex = S.Sex, 
				E.SireName = S.SireName,
				E.SiresSire = S.SiresSire, 
				E.Dam = S.Dam, 
				E.DamsSire = S.DamsSire, 
				E.TrainerName = S.TrainerName, 
				E.BreederName = S.BreederName, 
				E.TrainerStarts = S.TrainerStarts, 
				E.TrainerWins = S.TrainerWins, 
				E.TrainerPlaces = S.TrainerPlaces, 
				E.TrainerShows = S.TrainerShows, 
				E.TrainerPercentage = S.TrainerPercentage, 
				E.LasixInd = S.LasixInd, 
				E.ButeInd = S.ButeInd, 
				E.WeightAssigned = S.WeightAssigned, 
				E.ApprenticeWtAllowance = S.ApprenticeWtAllowance, 
				E.JockeyName = S.JockeyName, 
				E.JockeyID = (SELECT JockeyID FROM Jockeys WHERE JockeyName = S.JockeyName),
				E.JockeyStarts = S.JockeyStarts, 
				E.JockeyWins = S.JockeyWins, 
				E.JockeyPlaces = S.JockeyPlaces, 
				E.JockeyShows = S.JockeyShows, 
				E.JockeyPercentage = S.JockeyPercentage, 
				E.ClaimingPrice = S.ClaimingPrice, 
				E.LifetimeStarts = S.LifetimeStarts, 
				E.LifetimeWins = S.LifetimeWins, 
				E.LifetimePlaces = S.LifetimePlaces, 
				E.LifetimeShows = S.LifetimeShows, 
				E.LifetimeEarnings = S.LifetimeEarnings, 
				E.TrackStarts = S.TrackStarts, 
				E.TrackWins = S.TrackWins, 
				E.TrackPlaces = S.TrackPlaces, 
				E.TrackShows = S.TrackShows, 
				E.TrackEarnings = S.TrackEarnings, 
				E.TurfStarts = S.TurfStarts, 
				E.TurfWins = S.TurfWins, 
				E.TurfPlaces = S.TurfPlaces, 
				E.TurfShows = S.TurfShows, 
				E.TurfEarnings = S.TurfEarnings, 
				E.WetStarts = S.WetStarts, 
				E.WetWins = S.WetWins, 
				E.WetPlaces = S.WetPlaces, 
				E.WetShows = S.WetShows, 
				E.WetEarnings = S.WetEarnings, 
				E.DistanceStarts = S.DistanceStarts, 
				E.DistanceWins = S.DistanceWins, 
				E.DistancePlaces = S.DistancePlaces, 
				E.DistanceShows = S.DistanceShows, 
				E.DistanceEarnings = S.DistanceEarnings, 
				E.AlsoEligibleInd = S.AlsoEligibleInd, 
				E.PartOfFieldInd = S.PartOfFieldInd, 
				E.BlinkersToday = S.BlinkersToday, 
				E.BandagesTodayInd = S.BandagesTodayInd, 
				E.JockeyStatsYTD = S.JockeyStatsYTD,
				E.TrainerStatsYTD = S.TrainerStatsYTD,
				E.ReservedString3 = S.ReservedString3,
				E.ReservedString4 = S.ReservedString4,
				E.PostPosition = S.PostPosition, 
				E.OffTrackRating = S.OffTrackRating, 
				E.TurfRating = S.TurfRating, 
				E.FirstTimeLasix = S.FirstTimeLasix
    WHEN NOT MATCHED THEN  
		INSERT (
					RacID,
					RaceDt,
					TrackCd,
					RaceNum,
					HorseName,
					HorseID,
					PolePosition,
					MorningLine,
					PaceLines,
					EntryChar,
					ScratchFlagInd,
					CurrentYr,
					StartsThisYr,
					WinThisYr,
					PlacesThisYr,
					ShowsThisYr,
					EarningThisYr,
					PrevYearForEarning,
					StartsPrevYr,
					WinPrevYr,
					PlacesPrevYr,
					ShowsPrevYr,
					EarningPrevYr,
					OwnerName,
					Color,
					YearBorn,
					MonthBorn,
					StateBredInd,
					Age,
					Sex,
					SireName,
					SiresSire,
					Dam,
					DamsSire,
					TrainerName,
					BreederName,
					TrainerStarts,
					TrainerWins,
					TrainerPlaces,
					TrainerShows,
					TrainerPercentage,
					LasixInd,
					ButeInd,
					WeightAssigned,
					ApprenticeWtAllowance,
					JockeyName,
					JockeyID,
					JockeyStarts,
					JockeyWins,
					JockeyPlaces,
					JockeyShows,
					JockeyPercentage,
					ClaimingPrice,
					LifetimeStarts,
					LifetimeWins,
					LifetimePlaces,
					LifetimeShows,
					LifetimeEarnings,
					TrackStarts,
					TrackWins,
					TrackPlaces,
					TrackShows,
					TrackEarnings,
					TurfStarts,
					TurfWins,
					TurfPlaces,
					TurfShows,
					TurfEarnings,
					WetStarts,
					WetWins,
					WetPlaces,
					WetShows,
					WetEarnings,
					DistanceStarts,
					DistanceWins,
					DistancePlaces,
					DistanceShows,
					DistanceEarnings,
					AlsoEligibleInd,
					PartOfFieldInd,
					BlinkersToday,
					BandagesTodayInd,
					JockeyStatsYTD,
					TrainerStatsYTD,
					ReservedString3,
					ReservedString4,
					PostPosition,
					OffTrackRating,
					TurfRating,
					FirstTimeLasix
			   )
			   VALUES
			   (
					(SELECT RacID FROM kelso.rac WHERE RaceDt = S.RaceDt AND TrackCd = S.TrackCd AND RaceNum = S.RaceNum),
					S.RaceDt,
					S.TrackCd, 
					S.RaceNum,
					S.HorseName,
					(SELECT HorseID FROM kelso.Horses WHERE HorseName = S.HorseName),
					S.PolePosition,
					S.MorningLine,
					S.PaceLines,
					S.EntryChar,
					S.ScratchFlagInd,
					S.CurrentYr,
					S.StartsThisYr,
					S.WinThisYr,
					S.PlacesThisYr,
					S.ShowsThisYr,
					S.EarningThisYr,
					S.PrevYearForEarning,
					S.StartsPrevYr,
					S.WinPrevYr,
					S.PlacesPrevYr,
					S.ShowsPrevYr,
					S.EarningPrevYr,
					S.OwnerName,
					S.Color,
					S.YearBorn,
					S.MonthBorn,
					S.StateBredInd,
					S.Age,
					S.Sex,
					S.SireName,
					S.SiresSire,
					S.Dam,
					S.DamsSire,
					S.TrainerName,
					S.BreederName,
					S.TrainerStarts,
					S.TrainerWins,
					S.TrainerPlaces,
					S.TrainerShows,
					S.TrainerPercentage,
					S.LasixInd,
					S.ButeInd,
					S.WeightAssigned,
					S.ApprenticeWtAllowance,
					S.JockeyName,
					(SELECT JockeyID FROM kelso.Jockeys WHERE JockeyName = S.JockeyName),
					S.JockeyStarts,
					S.JockeyWins,
					S.JockeyPlaces,
					S.JockeyShows,
					S.JockeyPercentage,
					S.ClaimingPrice,
					S.LifetimeStarts,
					S.LifetimeWins,
					S.LifetimePlaces,
					S.LifetimeShows,
					S.LifetimeEarnings,
					S.TrackStarts,
					S.TrackWins,
					S.TrackPlaces,
					S.TrackShows,
					S.TrackEarnings,
					S.TurfStarts,
					S.TurfWins,
					S.TurfPlaces,
					S.TurfShows,
					S.TurfEarnings,
					S.WetStarts,
					S.WetWins,
					S.WetPlaces,
					S.WetShows,
					S.WetEarnings,
					S.DistanceStarts,
					S.DistanceWins,
					S.DistancePlaces,
					S.DistanceShows,
					S.DistanceEarnings,
					S.AlsoEligibleInd,
					S.PartOfFieldInd,
					S.BlinkersToday,
					S.BandagesTodayInd,
					S.JockeyStatsYTD,
					S.TrainerStatsYTD,
					S.ReservedString3,
					S.ReservedString4,
					S.PostPosition,
					S.OffTrackRating,
					S.TurfRating,
					S.FirstTimeLasix
			   );
END

GO






